export * from '@openuxkit/styled';

// Re-exported so consumers — including themes generated by the Theme Designer — can write
// `import type { Preset } from '@openvue/themes'` instead of reaching into the engine package.
export type { Preset } from '@openuxkit/themes/types';
