/* eslint-disable */
// generated by unplugin-vue-components
export {};

declare module 'vue' {
    export interface GlobalComponents {
        Button: typeof import('primevue/button')['default'];
        Toast: typeof import('primevue/toast')['default'];
    }
}
