import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, dirname, extname, join, relative } from 'node:path';
import { addCompatAlias, PackageManager, rewritePackageJson, rewriteSource, rewriteWorkspaceYaml } from './rewrite';
import { walk } from './walk';

const SOURCE_EXTENSIONS = new Set(['.js', '.mjs', '.cjs', '.ts', '.mts', '.cts', '.jsx', '.tsx', '.vue', '.astro', '.mdx']);
const AUDIT_EXTRA_EXTENSIONS = new Set(['.css', '.scss', '.sass', '.less', '.styl', '.html', '.json', '.yaml', '.yml']);

// A bare 'primevue' string is a package reference anywhere in these files, not only after import/require.
const CONFIG_FILE = /(^|\.)config\.[cm]?[jt]s$/i;

// Package-reference shapes that should not survive a migration: a string literal starting with
// `primevue` or `primevue/`, any `@primevue/` occurrence, or a CDN url segment like `/primevue@4`.
const RESIDUAL_REFERENCE = /['"`]primevue(?=[/'"`])|@primevue\/|\/primevue@/;

export type MigrateMode = 'full' | 'sources-only';

// Windows editors often save package.json with a UTF-8 BOM, which JSON.parse rejects.
function readText(file: string): string {
    const text = readFileSync(file, 'utf8');

    return text.charCodeAt(0) === 0xfeff ? text.slice(1) : text;
}

export interface MigrateOptions {
    dir: string;
    dry?: boolean;
    alias?: boolean;
}

export interface ChangedFile {
    file: string;
    changes: number;
    renamed?: string[];
}

export interface ResidualReference {
    file: string;
    line: number;
    text: string;
}

export interface MigrateResult {
    mode: MigrateMode;
    changedFiles: ChangedFile[];
    warnings: string[];
    notes: string[];
    residuals: ResidualReference[];
    // The migration is incomplete in a way the user must fix before installing (e.g. the root
    // package.json could not be rewritten) — the CLI must not install and must exit non-zero.
    failed: boolean;
    oldPrimevueRange: string | null;
    packageManager: PackageManager;
    installCommand: string;
}

/**
 * A project that already declares or installed OpenVue has handled the dependency switch itself —
 * the migration then only rewrites source files and must not touch package.json or node_modules.
 */
export function hasOpenVue(dir: string): boolean {
    if (existsSync(join(dir, 'node_modules', 'openvue'))) return true;

    const packageJson = join(dir, 'package.json');

    if (!existsSync(packageJson)) return false;

    try {
        const pkg = JSON.parse(readText(packageJson));

        for (const section of ['dependencies', 'devDependencies']) {
            const deps = pkg[section];

            if (deps && typeof deps === 'object' && Object.keys(deps).some((key) => key === 'openvue' || key.startsWith('@openvue/'))) return true;
        }
    } catch {
        // unparsable package.json — treat as not migrated
    }

    return false;
}

/**
 * Detects the package manager from lockfiles or the packageManager field, walking up parent
 * directories so running from a workspace package still reports the monorepo's real manager.
 */
export function detectPackageManager(dir: string): PackageManager {
    let current = dir;

    for (;;) {
        if (existsSync(join(current, 'pnpm-lock.yaml')) || existsSync(join(current, 'pnpm-workspace.yaml'))) return 'pnpm';
        if (existsSync(join(current, 'yarn.lock'))) return 'yarn';
        if (existsSync(join(current, 'bun.lock')) || existsSync(join(current, 'bun.lockb'))) return 'bun';
        if (existsSync(join(current, 'package-lock.json'))) return 'npm';

        const packageJson = join(current, 'package.json');

        if (existsSync(packageJson)) {
            try {
                const field = JSON.parse(readText(packageJson)).packageManager;
                const name = typeof field === 'string' ? field.split('@')[0] : '';

                if (name === 'pnpm' || name === 'yarn' || name === 'bun' || name === 'npm') return name;
            } catch {
                // unparsable package.json — keep walking up
            }
        }

        const parent = dirname(current);

        if (parent === current) return 'npm';
        current = parent;
    }
}

const INSTALL_COMMANDS: Record<PackageManager, string> = {
    npm: 'npm install',
    pnpm: 'pnpm install',
    yarn: 'yarn install',
    bun: 'bun install'
};

// Lockfiles are regenerated by the install step, so their stale references are not actionable.
const LOCKFILES = new Set(['package-lock.json', 'npm-shrinkwrap.json', 'pnpm-lock.yaml', 'yarn.lock', 'bun.lock']);

function isAuditFile(file: string): boolean {
    const name = basename(file);

    if (LOCKFILES.has(name)) return false;

    return SOURCE_EXTENSIONS.has(extname(file)) || AUDIT_EXTRA_EXTENSIONS.has(extname(file)) || name === 'package.json' || /^(tsconfig|jsconfig)[^/\\]*\.json$/.test(name);
}

/**
 * Scans for PrimeVue references that survived the rewrite (interpolated template literals, CSS
 * imports, tsconfig paths, CDN urls, intentionally kept keys) so the CLI never reports success
 * while actionable references remain.
 */
export function auditResiduals(dir: string, files: string[]): ResidualReference[] {
    const residuals: ResidualReference[] = [];

    for (const file of files) {
        if (!isAuditFile(file)) continue;

        const lines = readText(file).split('\n');

        for (let i = 0; i < lines.length; i++) {
            // The compat alias this tool writes is the one intended remaining reference.
            if (RESIDUAL_REFERENCE.test(lines[i]) && !lines[i].includes('npm:openvue')) {
                residuals.push({ file: relative(dir, file).replace(/\\/g, '/'), line: i + 1, text: lines[i].trim() });
            }
        }
    }

    return residuals;
}

/**
 * Runs the PrimeVue -> OpenVue migration over a project directory.
 * Pure file transformation — git preflight, install and console output live in the CLI.
 */
export function migrate(options: MigrateOptions): MigrateResult {
    const { dir, dry = false, alias = true } = options;
    const mode: MigrateMode = hasOpenVue(dir) ? 'sources-only' : 'full';
    const changedFiles: ChangedFile[] = [];
    const warnings: string[] = [];
    const notes: string[] = [];
    const skippedKeyFiles = new Set<string>();
    const unknownScoped = new Set<string>();
    const files = walk(dir);
    let oldPrimevueRange: string | null = null;
    let rootPackageJsonFailed = false;

    for (const file of files) {
        const name = basename(file);
        const displayPath = relative(dir, file).replace(/\\/g, '/');

        if (mode === 'sources-only' && (name === 'package.json' || name === 'pnpm-workspace.yaml')) continue;

        if (name === 'package.json') {
            const text = readText(file);
            let result;

            try {
                result = rewritePackageJson(text);
            } catch {
                warnings.push(`${displayPath}: could not be parsed as JSON, skipped.`);
                if (displayPath === 'package.json') rootPackageJsonFailed = true;
                continue;
            }

            if (result.oldPrimevueRange !== null && oldPrimevueRange === null) oldPrimevueRange = result.oldPrimevueRange;

            result.unknownScoped.forEach((pkg) => unknownScoped.add(pkg));
            result.notes.forEach((note) => notes.push(`${displayPath}: ${note}`));

            if (result.changed) {
                if (!dry) writeFileSync(file, result.text);
                changedFiles.push({ file: displayPath, changes: result.renamed.length + result.notes.length, renamed: result.renamed });
            }
        } else if (name === 'pnpm-workspace.yaml') {
            const text = readFileSync(file, 'utf8');
            const result = rewriteWorkspaceYaml(text);

            if (result.count > 0) {
                if (!dry) writeFileSync(file, result.text);
                changedFiles.push({ file: displayPath, changes: result.count });
            }
        } else if (SOURCE_EXTENSIONS.has(extname(file))) {
            const text = readFileSync(file, 'utf8');
            const result = rewriteSource(text, { configFile: CONFIG_FILE.test(name) });

            if (result.skippedKeys.length > 0) skippedKeyFiles.add(displayPath);
            result.unknownScoped.forEach((pkg) => unknownScoped.add(pkg));

            if (result.count > 0) {
                if (!dry) writeFileSync(file, result.code);
                changedFiles.push({ file: displayPath, changes: result.count });
            }
        }
    }

    const packageManager = detectPackageManager(dir);
    const rootPackageJson = join(dir, 'package.json');

    if (mode === 'full' && alias && changedFiles.length > 0 && !rootPackageJsonFailed && existsSync(rootPackageJson)) {
        try {
            const result = addCompatAlias(readText(rootPackageJson), packageManager);

            if (result.added) {
                if (!dry) writeFileSync(rootPackageJson, result.text);
                notes.push(`package.json: ${dry ? 'would add' : 'added'} override "primevue" -> "npm:openvue" so third-party libraries that (peer-)depend on primevue resolve to OpenVue. Remove it once your dependencies are OpenVue-native.`);
            }
        } catch {
            warnings.push('package.json: could not add the primevue -> openvue compatibility override; add it manually if any of your dependencies require primevue.');
        }
    }

    if (oldPrimevueRange !== null) {
        const majorMatch = /\d+/.exec(oldPrimevueRange);
        const major = majorMatch ? parseInt(majorMatch[0], 10) : null;

        if (major !== null && major < 4) {
            warnings.push(
                `Your project used primevue@${oldPrimevueRange}, which predates the OpenVue fork point (PrimeVue 4.x). Apply the PrimeVue v${major} -> v4 migration guide before or after this codemod — renaming packages alone will not be enough.`
            );
        }
    }

    for (const file of skippedKeyFiles) {
        warnings.push(`${file}: found a quoted 'primevue' object key and left it unchanged — the Nuxt module config key is still 'primevue' in OpenVue. Review it if it was meant as something else (e.g. a bundler alias).`);
    }

    for (const pkg of unknownScoped) {
        warnings.push(`${pkg} is not a package OpenVue publishes; it was left unchanged. Review it manually.`);
    }

    const residuals = dry ? [] : auditResiduals(dir, files);

    return { mode, changedFiles, warnings, notes, residuals, failed: rootPackageJsonFailed, oldPrimevueRange, packageManager, installCommand: INSTALL_COMMANDS[packageManager] };
}
