import { describe, expect, it } from 'vitest';
import { slugify, toFileName, toIdentifier, toPresetSource, toThemeJson } from '../../service/designer/codegen';
import { deepDiff } from '../../service/designer/diff';
import { SCHEMA_VERSION, THEME_FORMAT } from '../../service/designer/document';

const BASE = {
    primitive: { green: { 500: '#22c55e' }, blue: { 500: '#3b82f6' } },
    semantic: { primary: { color: '{green.500}' } },
    components: { button: { root: { borderRadius: '6px', paddingX: '1rem' } } }
};

/**
 * @param {object} [overrides]
 * @returns {object} a document whose preset differs from BASE in two places
 */
function doc(overrides = {}) {
    const preset = structuredClone(BASE);

    preset.semantic.primary.color = '{blue.500}';
    preset.components.button.root.borderRadius = '0px';

    return {
        format: THEME_FORMAT,
        schemaVersion: SCHEMA_VERSION,
        id: 'local-id',
        name: 'My Theme',
        base: 'Aura',
        preset,
        config: { font_size: '14px', font_family: 'Inter var' },
        createdAt: 1,
        updatedAt: 2,
        ...overrides
    };
}

/**
 * Pull the object literal out of generated source so it can be evaluated on its own.
 *
 * @param {string} source
 * @returns {string}
 */
function extractOverridesLiteral(source) {
    const start = source.indexOf('const overrides = ');
    const end = source.indexOf('\n\nexport const');

    return source.slice(start + 'const overrides = '.length, end).replace(/;$/, '');
}

describe('designer/codegen', () => {
    describe('naming', () => {
        it('slugifies for filenames', () => {
            expect(slugify('My Theme')).toBe('my-theme');
            expect(slugify('  Spaced  Out  ')).toBe('spaced-out');
            expect(slugify('Theme!!! v2')).toBe('theme-v2');
            expect(slugify('')).toBe('theme');
            expect(slugify('!!!')).toBe('theme');
        });

        it('builds a valid identifier', () => {
            expect(toIdentifier('My Theme')).toBe('MyTheme');
            expect(toIdentifier('123')).toBe('CustomTheme');
            expect(toIdentifier('')).toBe('CustomTheme');
        });

        it('names files by kind', () => {
            expect(toFileName(doc(), 'json')).toBe('my-theme.openvue-theme.json');
            expect(toFileName(doc(), 'ts')).toBe('my-theme.preset.ts');
        });
    });

    describe('toPresetSource', () => {
        it('emits the expected TypeScript module', () => {
            const source = toPresetSource(doc(), { mode: 'diff', language: 'ts', basePreset: BASE });

            expect(source).toBe(
                [
                    '/**',
                    ' * My Theme — generated by the OpenVue Theme Designer.',
                    ' *',
                    ' * Typography is a preview-only setting and is intentionally not part of the preset.',
                    ' * Apply these at the document level in your own application:',
                    ' *   font-family: Inter var',
                    ' *   root font-size: 14px',
                    ' */',
                    "import { definePreset } from '@openvue/themes';",
                    "import Aura from '@openvue/themes/aura';",
                    "import type { Preset } from '@openvue/themes';",
                    '',
                    'const overrides = {',
                    '    semantic: {',
                    '        primary: {',
                    "            color: '{blue.500}'",
                    '        }',
                    '    },',
                    '    components: {',
                    '        button: {',
                    '            root: {',
                    "                borderRadius: '0px'",
                    '            }',
                    '        }',
                    '    }',
                    '} satisfies Preset;',
                    '',
                    'export const MyTheme = definePreset(Aura, overrides);',
                    '',
                    'export default MyTheme;',
                    ''
                ].join('\n')
            );
        });

        it('omits the type import and satisfies clause in JavaScript mode', () => {
            const source = toPresetSource(doc(), { mode: 'diff', language: 'js', basePreset: BASE });

            expect(source).not.toContain('import type');
            expect(source).not.toContain('satisfies Preset');
        });

        it('omits the satisfies clause when asked, but keeps TypeScript otherwise', () => {
            const source = toPresetSource(doc(), { mode: 'diff', language: 'ts', basePreset: BASE, satisfies: false });

            expect(source).not.toContain('satisfies Preset');
            expect(source).not.toContain('import type');
        });

        it('emits the whole preset in full mode', () => {
            const source = toPresetSource(doc(), { mode: 'full', language: 'ts', basePreset: BASE });

            expect(source).toContain('primitive');
            expect(source).toContain('paddingX');
        });

        it('quotes numeric keys so the literal parses', () => {
            const source = toPresetSource(doc({ preset: { primitive: { green: { 500: '#000' } } } }), { mode: 'full', language: 'js' });

            expect(source).toContain("'500': '#000'");
        });

        it('escapes quotes and backslashes in values', () => {
            const source = toPresetSource(doc({ preset: { semantic: { font: "it's \\ odd" } } }), { mode: 'full', language: 'js' });

            expect(source).toContain("'it\\'s \\\\ odd'");
        });

        it('falls back to Aura for an unknown base', () => {
            const source = toPresetSource(doc({ base: 'Nonexistent' }), { mode: 'diff', language: 'ts', basePreset: BASE });

            expect(source).toContain("import Aura from '@openvue/themes/aura';");
        });

        it('imports the right specifier for each known base', () => {
            expect(toPresetSource(doc({ base: 'Aura' }), { mode: 'diff', basePreset: BASE })).toContain("import Aura from '@openvue/themes/aura';");
            expect(toPresetSource(doc({ base: 'Lara' }), { mode: 'diff', basePreset: BASE })).toContain("import Lara from '@openvue/themes/lara';");
            expect(toPresetSource(doc({ base: 'Material' }), { mode: 'diff', basePreset: BASE })).toContain("import Material from '@openvue/themes/material';");
            expect(toPresetSource(doc({ base: 'Nora' }), { mode: 'diff', basePreset: BASE })).toContain("import Nora from '@openvue/themes/nora';");
        });

        // Guards against emitting source that parses but means the wrong thing.
        it('generates a literal that evaluates back to the exact diff', () => {
            const source = toPresetSource(doc(), { mode: 'diff', language: 'js', basePreset: BASE });
            const evaluated = new Function('return ' + extractOverridesLiteral(source))();

            expect(evaluated).toEqual(deepDiff(BASE, doc().preset));
        });

        it('generates a full-mode literal that evaluates back to the whole preset', () => {
            const source = toPresetSource(doc(), { mode: 'full', language: 'js' });
            const evaluated = new Function('return ' + extractOverridesLiteral(source))();

            expect(evaluated).toEqual(doc().preset);
        });
    });

    describe('toThemeJson', () => {
        it('emits a portable document without local identity', () => {
            const parsed = JSON.parse(toThemeJson(doc(), '0.7.0'));

            expect(parsed.format).toBe(THEME_FORMAT);
            expect(parsed.schemaVersion).toBe(SCHEMA_VERSION);
            expect(parsed.libraryVersion).toBe('0.7.0');
            expect(parsed.id).toBeUndefined();
            expect(parsed.createdAt).toBeUndefined();
        });

        it('round-trips the preset unchanged', () => {
            expect(JSON.parse(toThemeJson(doc())).preset).toEqual(doc().preset);
        });
    });
});
