import Aura from '@primevue/themes/aura';
import Lara from '@primevue/themes/lara';
import Material from '@primevue/themes/material';
import Nora from '@primevue/themes/nora';
import type { Component } from 'vue';

export const componentLoaders = [
    'autocomplete',
    'calendar',
    'cascadeselect',
    'checkbox',
    'checkboxgroup',
    'chips',
    'colorpicker',
    'datepicker',
    'dropdown',
    'editor',
    'floatlabel',
    'fluid',
    'iconfield',
    'iftalabel',
    'inputchips',
    'inputgroup',
    'inputgroupaddon',
    'inputicon',
    'inputmask',
    'inputnumber',
    'inputotp',
    'inputswitch',
    'inputtext',
    'knob',
    'listbox',
    'multiselect',
    'password',
    'radiobutton',
    'radiobuttongroup',
    'rating',
    'select',
    'selectbutton',
    'slider',
    'textarea',
    'togglebutton',
    'toggleswitch',
    'treeselect',
    'button',
    'buttongroup',
    'speeddial',
    'splitbutton',
    'column',
    'row',
    'columngroup',
    'datatable',
    'dataview',
    'orderlist',
    'organizationchart',
    'paginator',
    'picklist',
    'tree',
    'treetable',
    'timeline',
    'virtualscroller',
    'accordion',
    'accordionpanel',
    'accordionheader',
    'accordioncontent',
    'accordiontab',
    'card',
    'deferredcontent',
    'divider',
    'fieldset',
    'panel',
    'scrollpanel',
    'splitter',
    'splitterpanel',
    'stepper',
    'steplist',
    'step',
    'stepitem',
    'steppanels',
    'steppanel',
    'tabview',
    'tabs',
    'tablist',
    'tab',
    'tabpanels',
    'tabpanel',
    'toolbar',
    'confirmdialog',
    'confirmpopup',
    'dialog',
    'drawer',
    'dynamicdialog',
    'overlaypanel',
    'popover',
    'sidebar',
    'fileupload',
    'breadcrumb',
    'contextmenu',
    'dock',
    'menu',
    'menubar',
    'megamenu',
    'panelmenu',
    'steps',
    'tabmenu',
    'tieredmenu',
    'chart',
    'message',
    'inlinemessage',
    'toast',
    'carousel',
    'galleria',
    'image',
    'imagecompare',
    'avatar',
    'avatargroup',
    'badge',
    'blockui',
    'chip',
    'inplace',
    'metergroup',
    'overlaybadge',
    'scrolltop',
    'skeleton',
    'progressbar',
    'progressspinner',
    'tag',
    'terminal'
] as const;

const imports: Record<(typeof componentLoaders)[number], () => Promise<unknown>> = {
    autocomplete: () => import('primevue/autocomplete'),
    calendar: () => import('primevue/calendar'),
    cascadeselect: () => import('primevue/cascadeselect'),
    checkbox: () => import('primevue/checkbox'),
    checkboxgroup: () => import('primevue/checkboxgroup'),
    chips: () => import('primevue/chips'),
    colorpicker: () => import('primevue/colorpicker'),
    datepicker: () => import('primevue/datepicker'),
    dropdown: () => import('primevue/dropdown'),
    editor: () => import('primevue/editor'),
    floatlabel: () => import('primevue/floatlabel'),
    fluid: () => import('primevue/fluid'),
    iconfield: () => import('primevue/iconfield'),
    iftalabel: () => import('primevue/iftalabel'),
    inputchips: () => import('primevue/inputchips'),
    inputgroup: () => import('primevue/inputgroup'),
    inputgroupaddon: () => import('primevue/inputgroupaddon'),
    inputicon: () => import('primevue/inputicon'),
    inputmask: () => import('primevue/inputmask'),
    inputnumber: () => import('primevue/inputnumber'),
    inputotp: () => import('primevue/inputotp'),
    inputswitch: () => import('primevue/inputswitch'),
    inputtext: () => import('primevue/inputtext'),
    knob: () => import('primevue/knob'),
    listbox: () => import('primevue/listbox'),
    multiselect: () => import('primevue/multiselect'),
    password: () => import('primevue/password'),
    radiobutton: () => import('primevue/radiobutton'),
    radiobuttongroup: () => import('primevue/radiobuttongroup'),
    rating: () => import('primevue/rating'),
    select: () => import('primevue/select'),
    selectbutton: () => import('primevue/selectbutton'),
    slider: () => import('primevue/slider'),
    textarea: () => import('primevue/textarea'),
    togglebutton: () => import('primevue/togglebutton'),
    toggleswitch: () => import('primevue/toggleswitch'),
    treeselect: () => import('primevue/treeselect'),
    button: () => import('primevue/button'),
    buttongroup: () => import('primevue/buttongroup'),
    speeddial: () => import('primevue/speeddial'),
    splitbutton: () => import('primevue/splitbutton'),
    column: () => import('primevue/column'),
    row: () => import('primevue/row'),
    columngroup: () => import('primevue/columngroup'),
    datatable: () => import('primevue/datatable'),
    dataview: () => import('primevue/dataview'),
    orderlist: () => import('primevue/orderlist'),
    organizationchart: () => import('primevue/organizationchart'),
    paginator: () => import('primevue/paginator'),
    picklist: () => import('primevue/picklist'),
    tree: () => import('primevue/tree'),
    treetable: () => import('primevue/treetable'),
    timeline: () => import('primevue/timeline'),
    virtualscroller: () => import('primevue/virtualscroller'),
    accordion: () => import('primevue/accordion'),
    accordionpanel: () => import('primevue/accordionpanel'),
    accordionheader: () => import('primevue/accordionheader'),
    accordioncontent: () => import('primevue/accordioncontent'),
    accordiontab: () => import('primevue/accordiontab'),
    card: () => import('primevue/card'),
    deferredcontent: () => import('primevue/deferredcontent'),
    divider: () => import('primevue/divider'),
    fieldset: () => import('primevue/fieldset'),
    panel: () => import('primevue/panel'),
    scrollpanel: () => import('primevue/scrollpanel'),
    splitter: () => import('primevue/splitter'),
    splitterpanel: () => import('primevue/splitterpanel'),
    stepper: () => import('primevue/stepper'),
    steplist: () => import('primevue/steplist'),
    step: () => import('primevue/step'),
    stepitem: () => import('primevue/stepitem'),
    steppanels: () => import('primevue/steppanels'),
    steppanel: () => import('primevue/steppanel'),
    tabview: () => import('primevue/tabview'),
    tabs: () => import('primevue/tabs'),
    tablist: () => import('primevue/tablist'),
    tab: () => import('primevue/tab'),
    tabpanels: () => import('primevue/tabpanels'),
    tabpanel: () => import('primevue/tabpanel'),
    toolbar: () => import('primevue/toolbar'),
    confirmdialog: () => import('primevue/confirmdialog'),
    confirmpopup: () => import('primevue/confirmpopup'),
    dialog: () => import('primevue/dialog'),
    drawer: () => import('primevue/drawer'),
    dynamicdialog: () => import('primevue/dynamicdialog'),
    overlaypanel: () => import('primevue/overlaypanel'),
    popover: () => import('primevue/popover'),
    sidebar: () => import('primevue/sidebar'),
    fileupload: () => import('primevue/fileupload'),
    breadcrumb: () => import('primevue/breadcrumb'),
    contextmenu: () => import('primevue/contextmenu'),
    dock: () => import('primevue/dock'),
    menu: () => import('primevue/menu'),
    menubar: () => import('primevue/menubar'),
    megamenu: () => import('primevue/megamenu'),
    panelmenu: () => import('primevue/panelmenu'),
    steps: () => import('primevue/steps'),
    tabmenu: () => import('primevue/tabmenu'),
    tieredmenu: () => import('primevue/tieredmenu'),
    chart: () => import('primevue/chart'),
    message: () => import('primevue/message'),
    inlinemessage: () => import('primevue/inlinemessage'),
    toast: () => import('primevue/toast'),
    carousel: () => import('primevue/carousel'),
    galleria: () => import('primevue/galleria'),
    image: () => import('primevue/image'),
    imagecompare: () => import('primevue/imagecompare'),
    avatar: () => import('primevue/avatar'),
    avatargroup: () => import('primevue/avatargroup'),
    badge: () => import('primevue/badge'),
    blockui: () => import('primevue/blockui'),
    chip: () => import('primevue/chip'),
    inplace: () => import('primevue/inplace'),
    metergroup: () => import('primevue/metergroup'),
    overlaybadge: () => import('primevue/overlaybadge'),
    scrolltop: () => import('primevue/scrolltop'),
    skeleton: () => import('primevue/skeleton'),
    progressbar: () => import('primevue/progressbar'),
    progressspinner: () => import('primevue/progressspinner'),
    tag: () => import('primevue/tag'),
    terminal: () => import('primevue/terminal')
};

export interface SurfaceComponent {
    name: string;
    component: Component;
}

export async function loadPublicSurface(): Promise<SurfaceComponent[]> {
    void [Aura, Lara, Material, Nora];
    const loaded = await Promise.all(
        Object.entries(imports).map(async ([name, load]) => {
            const module = (await load()) as { default: Component };

            return { name, component: module.default };
        })
    );
    const [{ default: Form }, { default: FormField }] = await Promise.all([import('@primevue/forms/form'), import('@primevue/forms/formfield')]);

    await Promise.all([import('@primevue/forms'), import('@primevue/icons'), import('@primevue/themes')]);

    return [...loaded, { name: 'form', component: Form }, { name: 'formfield', component: FormField }];
}
