name: Daily Build

on:
    schedule:
        - cron: '0 6 * * *'

permissions:
    contents: read

jobs:
    nightly:
        if: github.repository == 'openvi-foundation/openvue' && github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest
        name: Node ${{ matrix.node-version }}

        strategy:
            matrix:
                node-version: [20, 22, 24]

        steps:
            - name: Checkout repository
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

            - name: Install pnpm
              uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
              with:
                  version: 9.15.9

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: Build
              run: |
                  pnpm install --frozen-lockfile
                  pnpm run build:lib
